proxy_urls:
  - path: "/localhost"
    url: "http://localhost:9000"
    query:
      - name: "q"
        value: "12"
      - name: "wt"
        value: "12"
  - path: "/my-ip"
    url: "https://api.my-ip.io/ip"
  - path: "/nyaa"
    url: "https://nyaa.si/"
    query:
      - name: "page"
        value: "rss"
      - name: "c"
        value: "3_1"
      - name: "f"
        value: "0"
haloo: string