proxy_urls:
  - path: "/my-ip"
    url: "http://ip-api.com/json"
    method: "get"
    headers:
      - name: "Accept"
        value: "application/json"
  - path: "/posts"
    url: "https://jsonplaceholder.typicode.com/posts"
    method: "get"
    target_method: "get"
    headers:
      - name: "Accept"
        value: "application/json"
  - path: "/posts"
    url: "https://jsonplaceholder.typicode.com/posts"
    method: "post"
    default_body: |
      {
        "title": "foo",
        "body": "bar",
        "userId": 1
      }
    headers:
      - name: "Accept"
        value: "application/json"
      - name: "Content-Type"
        value: "application/json"
